#!/usr/bin/env python3
"""Desktop integration: shortcut round-trips and theme parsing.

Runs headless against a throwaway HOME — no compositor, no real config touched.
What it pins down:

* the Hyprland/Omarchy managed block is written, read back, and removed without
  disturbing a single other line of the user's config;
* a plain-Hyprland install gets its own file plus exactly one `source =` line,
  however many times the shortcut is changed;
* `colors.toml` parses -- including the one that bit us: the values are
  `"#89b4fa"`, so a naive "strip everything after #" comment rule silently
  eats every colour and the theme falls back to the built-in palette;
* a theme only colours the mode it *is*, so a dark theme never repaints a
  light panel.
"""
from __future__ import annotations

import os
import sys
import tempfile
from pathlib import Path

FAILED = []


def check(label, got, want):
    if got == want:
        print(f"  ok   {label}")
    else:
        print(f"  FAIL {label}\n         got:  {got!r}\n         want: {want!r}")
        FAILED.append(label)


def check_true(label, got):
    check(label, bool(got), True)


def fresh_home():
    """A temp HOME, with clippy.desktops re-imported to bind to it."""
    tmp = tempfile.mkdtemp(prefix="clippy-desktops-test-")
    os.environ["HOME"] = tmp
    for mod in [m for m in sys.modules if m.startswith("clippy")]:
        del sys.modules[mod]
    return Path(tmp)


# --- Omarchy: a managed block in bindings.lua -----------------------------
def test_omarchy_shortcut():
    print("omarchy shortcut")
    home = fresh_home()
    hypr = home / ".config" / "hypr"
    hypr.mkdir(parents=True)
    original = (
        "-- my own bindings\n"
        'o.bind("SUPER + SHIFT + R", "SSH", "alacritty -e ssh box")\n'
        'hl.unbind("SUPER + SHIFT + B")\n'
    )
    (hypr / "bindings.lua").write_text(original)

    from clippy.desktops.hyprland import HyprlandDesktop
    d = HyprlandDesktop()
    check("dialect is omarchy", d.omarchy, True)
    check("label", d.label, "Omarchy")
    check("nothing bound yet", d.read_shortcut(), None)

    d._reload = lambda: None   # never touch the developer's live compositor
    check_true("set_shortcut", d.set_shortcut(["Super", "Shift"], "v", "/usr/bin/clippy toggle"))
    check("round-trips", d.read_shortcut(), (["Super", "Shift"], "v"))

    text = (hypr / "bindings.lua").read_text()
    check_true("user's bindings survive", original.strip() in text)
    check_true("emits an unbind first", 'hl.unbind("SUPER + SHIFT + V")' in text)
    check_true("binds the command", '"/usr/bin/clippy toggle"' in text)

    # Re-binding must replace, never accumulate.
    d.set_shortcut(["Super"], "grave", "/usr/bin/clippy toggle")
    text = (hypr / "bindings.lua").read_text()
    check("one managed block only", text.count("-- >>> clippy (managed) >>>"), 1)
    check("non-letter key kept verbatim", d.read_shortcut(), (["Super"], "grave"))
    check_true("no stale V bind", "SUPER + SHIFT + V" not in text)

    check_true("remove_shortcut", d.remove_shortcut())
    check("block gone", d.read_shortcut(), None)
    check("file restored to the user's own lines",
          (hypr / "bindings.lua").read_text().strip(), original.strip())


# --- plain Hyprland: our own file, sourced once ---------------------------
def test_plain_hyprland_shortcut():
    print("plain hyprland shortcut")
    home = fresh_home()
    hypr = home / ".config" / "hypr"
    hypr.mkdir(parents=True)
    (hypr / "hyprland.conf").write_text("monitor = ,preferred,auto,1\n")

    from clippy.desktops.hyprland import HyprlandDesktop
    d = HyprlandDesktop()
    d._reload = lambda: None
    check("dialect is plain", d.omarchy, False)
    check("label", d.label, "Hyprland")

    check_true("set_shortcut", d.set_shortcut(["Super", "Shift"], "v", "clippy toggle"))
    check("round-trips", d.read_shortcut(), (["Super", "Shift"], "v"))
    conf = (hypr / "hyprland.conf").read_text()
    check_true("monitor line survives", "monitor = ,preferred,auto,1" in conf)
    check("sourced once", conf.count("source ="), 1)
    check_true("binding is in our file, not theirs", "bind =" not in conf)
    check_true("our file has the bind",
               "bind = SUPER SHIFT, V, exec, clippy toggle"
               in (hypr / "clippy.conf").read_text())

    d.set_shortcut(["Ctrl", "Alt"], "c", "clippy toggle")
    check("still sourced once", (hypr / "hyprland.conf").read_text().count("source ="), 1)
    check("re-read", d.read_shortcut(), (["Ctrl", "Alt"], "c"))


# --- Omarchy theme --------------------------------------------------------
_COLORS = '''# Generated by Aether for Omarchy v4.
mode = "dark"

accent = "#89b4fa"
background = "#1e1e2e"
lighter_background = "#353543"
foreground = "#cdd6f4"
red = "#f38ba8"
orange = "#f59cb5"
'''


def test_omarchy_theme():
    print("omarchy theme")
    home = fresh_home()
    theme_dir = home / ".local" / "state" / "omarchy" / "current" / "theme"
    theme_dir.mkdir(parents=True)
    (theme_dir / "colors.toml").write_text(_COLORS)

    from clippy.desktops.hyprland import HyprlandDesktop
    d = HyprlandDesktop()
    check("mode read from colors.toml", d.is_dark(), True)

    p = d.palette(dark=True)
    # The regression: '#' opens a TOML comment *and* every value here starts
    # with one. Stripping comments before the quotes empties the whole palette.
    check_true("hex values are not eaten as comments", p != {})
    check("background", p.get("background"), (30 / 255, 30 / 255, 46 / 255))
    check("accent", p.get("accent"), (137 / 255, 180 / 255, 250 / 255))
    check("surface <- lighter_background", p.get("surface"), (53 / 255, 53 / 255, 67 / 255))
    check("danger <- red", p.get("danger"), (243 / 255, 139 / 255, 168 / 255))
    check("warning <- orange", p.get("warning"), (245 / 255, 156 / 255, 181 / 255))
    check("a dark theme does not colour the light palette", d.palette(dark=False), {})

    # A light theme flips both answers.
    (theme_dir / "colors.toml").write_text(_COLORS.replace('mode = "dark"', 'mode = "light"'))
    check("light mode read", d.is_dark(), False)
    check("light palette populated", "background" in d.palette(dark=False), True)
    check("light theme does not colour the dark palette", d.palette(dark=True), {})

    # A theme with no colors.toml must not explode.
    (theme_dir / "colors.toml").unlink()
    check("missing colors.toml -> built-ins", d.palette(dark=True), {})

    # theme.py must survive a desktop that reports nothing.
    from clippy import theme
    css = theme.build_css(True)
    check_true("css still builds with no desktop colours", len(css) > 1000)


# --- the fallback ---------------------------------------------------------
def test_generic():
    print("generic desktop")
    fresh_home()
    from clippy.desktops.generic import GenericDesktop
    d = GenericDesktop()
    check("always matches", d.detected(), True)
    check("cannot bind", d.can_bind(), False)
    check("set is a no-op", d.set_shortcut(["Super"], "v", "clippy toggle"), False)
    check("read is empty", d.read_shortcut(), None)
    check("no palette", d.palette(True), {})
    check("nothing to watch", d.theme_paths(), [])
    check_true("still explains itself", "clippy toggle" in d.shortcut_help("clippy toggle"))


def test_hex_parsing():
    print("hex parsing")
    fresh_home()
    from clippy.desktops.base import parse_hex
    check("6-digit", parse_hex("#ffffff"), (1.0, 1.0, 1.0))
    check("no hash", parse_hex("000000"), (0.0, 0.0, 0.0))
    check("3-digit", parse_hex("#f00"), (1.0, 0.0, 0.0))
    check("quoted", parse_hex('"#89b4fa"'), (137 / 255, 180 / 255, 250 / 255))
    check("garbage", parse_hex("not-a-colour"), None)
    check("empty", parse_hex(""), None)


def main() -> int:
    real_home = os.environ.get("HOME")
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
    try:
        test_omarchy_shortcut()
        test_plain_hyprland_shortcut()
        test_omarchy_theme()
        test_generic()
        test_hex_parsing()
    finally:
        if real_home:
            os.environ["HOME"] = real_home
    print()
    if FAILED:
        print(f"FAILED ({len(FAILED)}): " + ", ".join(FAILED))
        return 1
    print("desktops: all checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
